version: "3.9"

services:
  kratos-migrate:
    image: oryd/kratos:v0.8.0-alpha.2-sqlite
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - {LOCAL_VOLUME_KRATOS}/kratos.yml:/home/.kratos.yaml
    command: migrate sql -e --yes
    restart: on-failure
    networks:
      - default

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.8.0-alpha.2-sqlite
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - LOG_LEVEL=trace
      - SERVE_PUBLIC_BASE_URL=http://localhost:4455/.ory/kratos/public/
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    ports:
      - 4434:4434
    volumes:
      - {LOCAL_VOLUME_KRATOS}:/etc/config/kratos:Z
      - kratos-sqlite:/var/lib/sqlite
    networks:
      - default

  oathkeeper:
    image: oryd/oathkeeper:v0.38.15-beta.1
    depends_on:
      - kratos
    ports:
      - 4455:4455
    command: serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"
    environment:
      - LOG_LEVEL=debug
    restart: on-failure
    networks:
      - default
    volumes:
      - {LOCAL_VOLUME_OATHKEEPER}:/etc/config/oathkeeper:Z

  authorizer:
    image: ibiscp/authorizer:{AUTHORIZER}
    restart: always
    expose:
      - 80
    networks:
      - default

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 4436:8025
    networks:
      - default

  ui:
    image: ibiscp/ui:{UI}
    # build:
    #   context: ./modules/ui/
    #   dockerfile: Dockerfile
    restart: always
    ports:
      - 7050:80
    expose:
      - 80
    networks:
      - default

  entry:
    image: ibiscp/entry:{ENTRY}
    restart: always
    environment:    
      - IS_OS=1
    expose:
      - 80
    networks:
      - default

  postgres-migrate:
    depends_on:
      - graphql-postgres
    image: ibiscp/gateway:{GATEWAY}
    environment:
      - POSTGRES=postgresql://postgres:onetask@graphql-postgres:5432
    command: alembic upgrade head
    networks:
      - default

  gateway:
    depends_on:
      - config
    image: ibiscp/gateway:{GATEWAY}
    restart: always
    ports:
      - 7051:80
    expose:
      - 80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:Z
      - graphql-sqlite:/sqlite
    environment:
      - AC_EXEC_ENV_IMAGE=ibiscp/ac-exec-env:{AC_EXEC_ENV}
      - LF_EXEC_ENV_IMAGE=ibiscp/lf-exec-env:{LF_EXEC_ENV}
      - ML_EXEC_ENV_IMAGE=ibiscp/ml-exec-env:{ML_EXEC_ENV}
      - RECORD_IDE_IMAGE=ibiscp/record-ide-env:{RECORD_IDE_ENV}
      - POSTGRES=postgresql://postgres:onetask@graphql-postgres:5432
      - LF_NETWORK=refinery_default
      - WEAK_SUPERVISION=http://weak-supervisor:80
      - EMBEDDING_SERVICE=http://embedder:80
      # - EMBEDDING_SERVICE=http://host.docker.internal:2873
      - DOC_OCK=http://doc-ock:80
      # - TOKENIZER=http://tokenizer:80
      - TOKENIZER=http://host.docker.internal:2874
      - ZERO_SHOT=http://zero-shot:80
      - NEURAL_SEARCH=http://neural-search:80
      - KRATOS_ADMIN_URL=http://kratos:4434
      - WS_NOTIFY_ENDPOINT=http://websocket:8080
      - UPDATER=http://updater:80
      - CONFIG=http://config:80
      - S3_URI=object-storage:9000 # remove as soon as multipart upload is merged
      - S3_ENDPOINT={CRED_ENDPOINT}
      - S3_ENDPOINT_LOCAL=object-storage:9000
      - S3_ACCESS_KEY=onetask
      - S3_SECRET_KEY=JRZtI0SLsEDb3imTy03R
      - SQLITE=/sqlite/db.sqlite
      # - TYPESENSE_SEARCH=http://typesense-api:80
    networks:
      - default

  graphql-postgres:
    image: docker.io/postgres:13
    restart: always
    ports:
      - 7052:5432
    environment:
      - POSTGRES_PASSWORD=onetask
      - POSTGRES_USER=postgres
    expose:
      - 5432
    networks:
      - default
    volumes:
      - {LOCAL_VOLUME_POSTGRES}:/var/lib/postgresql/data
      
  qdrant:
    image: qdrant/qdrant:v0.9.1
    restart: always
    ports:
      - 6333:6333
    expose:
      - 6333
    networks:
      - default
    volumes:
      - {LOCAL_VOLUME_QDRANT}:/qdrant/storage

  gateway-proxy:
    depends_on:
      - graphql-postgres
    image: ibiscp/gateway-proxy:{GATEWAY_PROXY}
    restart: always
    expose:
      - 80
    environment:
      - POSTGRES=postgresql://postgres:onetask@postgres:5432
      - GATEWAY=http://gateway:80
      # - GATEWAY=http://host.docker.internal:7051
      - KRATOS=http://kratos:4433
      - CONFIG=http://config:80
    links:
      - "graphql-postgres:postgres"
    networks:
      - default

  object-storage:
    image: docker.io/minio/minio:latest
    restart: always
    ports:
      - 7053:9000
      - 9001:9001
    expose:
      - 9000
    environment:
      - MINIO_ROOT_USER=onetask
      - MINIO_ROOT_PASSWORD=JRZtI0SLsEDb3imTy03R
      - MINIO_NOTIFY_WEBHOOK_ENABLE=on
      - MINIO_NOTIFY_WEBHOOK_ENDPOINT=http://gateway:80/notify
      # - MINIO_NOTIFY_WEBHOOK_ENDPOINT=http://host.docker.internal:7051/notify
    command: server /data --address :9000 --console-address ":9001"
    networks:
      - default
    volumes:
      - {LOCAL_VOLUME_MINIO}:/data

  weak-supervisor:
    image: ibiscp/weak-supervisor:{WEAK_SUPERVISOR}
    restart: unless-stopped
    ports:
      - 7054:80
    expose:
      - 80
    environment:
      - POSTGRES=postgresql://postgres:onetask@graphql-postgres:5432
      - WS_NOTIFY_ENDPOINT=http://websocket:8080
    networks:
      - default

  embedder:
    image: ibiscp/embedder:{EMBEDDER}
    # build:
    #   context: ./modules/embedder/
    #   dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 7058:80
    environment:
      - POSTGRES=postgresql://postgres:onetask@graphql-postgres:5432
      - S3_ENDPOINT_LOCAL=object-storage:9000
      - S3_ACCESS_KEY=onetask
      - S3_SECRET_KEY=JRZtI0SLsEDb3imTy03R
      - DOC_OCK=http://doc-ock:80
      - WS_NOTIFY_ENDPOINT=http://websocket:8080
      - NEURAL_SEARCH=http://neural-search:80
      - CONFIG=http://config:80
    expose:
      - 80
    networks:
      - default

  config:
    image: ibiscp/config:{CONFIG}
    # build:
    #   context: ./modules/config/
    #   dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 7059:80
    environment:
      - IS_MANAGED=0
      - KERN_S3_ENDPOINT=http://localhost:7053
    expose:
      - 80
    networks:
      - default

  doc-ock:
    depends_on:
      - config
    image: ibiscp/doc-ock:{DOC_OCK}
    restart: unless-stopped
    ports:
      - 7060:80
    expose:
      - 80
    environment:
      - CONFIG=http://config:80
    #   - TELEMETRY_URI=https://telemetry.kern.ai

  websocket:
    image: ibiscp/websocket:{WEBSOCKET}
    restart: unless-stopped
    environment:
      - DB_DSN=postgresql://postgres:onetask@graphql-postgres:5432?sslmode=disable
    ports:
      - 7065:8080
    expose:
      - 8080
    networks:
      - default

  # tokenizer:
  #   depends_on:
  #     - config
  #   image: ibiscp/tokenizer:{TOKENIZER}
  #   restart: unless-stopped
  #   ports:
  #     - 7061:80
  #   environment:
  #     - POSTGRES=postgresql://postgres:onetask@graphql-postgres:5432
  #     - S3_ENDPOINT_LOCAL=object-storage:9000
  #     - S3_ACCESS_KEY=onetask
  #     - S3_SECRET_KEY=JRZtI0SLsEDb3imTy03R
  #     - DOC_OCK=http://doc-ock:80
  #     - WS_NOTIFY_ENDPOINT=http://websocket:8080
  #     - CONFIG=http://config:80
  #   expose:
  #     - 80
  #   networks:
  #     - default

  updater:
    image: ibiscp/updater:{UPDATER}
    restart: unless-stopped
    ports:
      - 7062:80
    environment:
      - NEURAL_SEARCH=http://neural-search:80
      - POSTGRES=postgresql://postgres:onetask@graphql-postgres:5432
      - S3_ENDPOINT_LOCAL=object-storage:9000
      - S3_ACCESS_KEY=onetask
      - S3_SECRET_KEY=JRZtI0SLsEDb3imTy03R
    expose:
      - 80
    networks:
      - default

  neural-search:
    image: ibiscp/neural-search:{NEURAL_SEARCH}
    restart: unless-stopped
    ports:
      - 7063:80
    environment:
      - POSTGRES=postgresql://postgres:onetask@graphql-postgres:5432
      - QDRANT_PORT=6333
    expose:
      - 80
    networks:
      - default

  zero-shot:
    image: ibiscp/zero-shot:{ZERO_SHOT}
    restart: unless-stopped
    ports:
      - 7064:80
    environment:
      - POSTGRES=postgresql://postgres:onetask@graphql-postgres:5432
      - WS_NOTIFY_ENDPOINT=http://websocket:8080
    expose:
      - 80
    networks:
      - default

networks:
  default:

volumes:
  kratos-sqlite:
  graphql-sqlite: